# Form implementation generated from reading ui file 'scores.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 320)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelStudents = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelStudents.setObjectName("labelStudents")
        self.gridLayout.addWidget(self.labelStudents, 0, 0, 1, 1)
        self.lineEditStudents = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditStudents.setObjectName("lineEditStudents")
        self.gridLayout.addWidget(self.lineEditStudents, 0, 1, 1, 1)
        self.labelScores = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelScores.setObjectName("labelScores")
        self.gridLayout.addWidget(self.labelScores, 1, 0, 1, 1)
        self.lineEditScores = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditScores.setObjectName("lineEditScores")
        self.gridLayout.addWidget(self.lineEditScores, 1, 1, 1, 1)
        self.pushButtonCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.gridLayout.addWidget(self.pushButtonCalculate, 2, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.textEditOutput = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEditOutput.setReadOnly(True)
        self.textEditOutput.setObjectName("textEditOutput")
        self.verticalLayout.addWidget(self.textEditOutput)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 480, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Student Scores"))
        self.labelStudents.setText(_translate("MainWindow", "Total number of students:"))
        self.labelScores.setText(_translate("MainWindow", "Enter score(s):"))
        self.pushButtonCalculate.setText(_translate("MainWindow", "Calculate Grades"))
