# Form implementation generated from reading ui file 'scores.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 257)
        MainWindow.setMinimumSize(QtCore.QSize(330, 257))
        MainWindow.setMaximumSize(QtCore.QSize(330, 257))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEditOutput = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEditOutput.setGeometry(QtCore.QRect(10, 110, 311, 79))
        self.textEditOutput.setReadOnly(True)
        self.textEditOutput.setObjectName("textEditOutput")
        self.labelStudents = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelStudents.setGeometry(QtCore.QRect(20, 10, 157, 16))
        self.labelStudents.setObjectName("labelStudents")
        self.labelScores = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelScores.setGeometry(QtCore.QRect(90, 40, 90, 16))
        self.labelScores.setObjectName("labelScores")
        self.lineEditScores = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditScores.setGeometry(QtCore.QRect(190, 40, 125, 21))
        self.lineEditScores.setObjectName("lineEditScores")
        self.pushButtonCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCalculate.setGeometry(QtCore.QRect(190, 70, 131, 32))
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")
        self.lineEditStudents = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditStudents.setGeometry(QtCore.QRect(190, 10, 125, 21))
        self.lineEditStudents.setObjectName("lineEditStudents")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 330, 38))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Student Scores"))
        self.labelStudents.setText(_translate("MainWindow", "Total number of students:"))
        self.labelScores.setText(_translate("MainWindow", "Enter score(s):"))
        self.pushButtonCalculate.setText(_translate("MainWindow", "Calculate Grades"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
