# Form implementation generated from reading ui file 'scores.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 300)
        MainWindow.setMinimumSize(QtCore.QSize(330, 300))
        MainWindow.setMaximumSize(QtCore.QSize(330, 300))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(10, 10, 311, 30))
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")

        self.labelName = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelName.setGeometry(QtCore.QRect(20, 50, 80, 20))
        self.labelName.setObjectName("labelName")

        self.lineEditName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditName.setGeometry(QtCore.QRect(120, 50, 180, 22))
        self.lineEditName.setObjectName("lineEditName")

        self.labelStudents = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelStudents.setGeometry(QtCore.QRect(20, 80, 180, 20))
        self.labelStudents.setObjectName("labelStudents")

        self.lineEditStudents = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditStudents.setGeometry(QtCore.QRect(200, 80, 100, 22))
        self.lineEditStudents.setObjectName("lineEditStudents")

        self.labelScore1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelScore1.setGeometry(QtCore.QRect(20, 115, 80, 20))
        self.labelScore1.setObjectName("labelScore1")

        self.lineEditScore1 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditScore1.setGeometry(QtCore.QRect(120, 115, 80, 22))
        self.lineEditScore1.setObjectName("lineEditScore1")

        self.labelScore2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelScore2.setGeometry(QtCore.QRect(20, 145, 80, 20))
        self.labelScore2.setObjectName("labelScore2")

        self.lineEditScore2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditScore2.setGeometry(QtCore.QRect(120, 145, 80, 22))
        self.lineEditScore2.setObjectName("lineEditScore2")

        self.labelScore3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelScore3.setGeometry(QtCore.QRect(20, 175, 80, 20))
        self.labelScore3.setObjectName("labelScore3")

        self.lineEditScore3 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditScore3.setGeometry(QtCore.QRect(120, 175, 80, 22))
        self.lineEditScore3.setObjectName("lineEditScore3")

        self.labelScore4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelScore4.setGeometry(QtCore.QRect(20, 205, 80, 20))
        self.labelScore4.setObjectName("labelScore4")

        self.lineEditScore4 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditScore4.setGeometry(QtCore.QRect(120, 205, 80, 22))
        self.lineEditScore4.setObjectName("lineEditScore4")

        self.pushButtonCalculate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCalculate.setGeometry(QtCore.QRect(210, 205, 90, 28))
        self.pushButtonCalculate.setObjectName("pushButtonCalculate")

        self.textEditOutput = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEditOutput.setGeometry(QtCore.QRect(20, 240, 280, 50))
        self.textEditOutput.setReadOnly(True)
        self.textEditOutput.setObjectName("textEditOutput")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Student Scores"))
        self.labelTitle.setText(_translate("MainWindow", "STUDENT SCORES"))
        self.labelName.setText(_translate("MainWindow", "Name"))
        self.labelStudents.setText(_translate("MainWindow", "Number of Scores"))
        self.labelScore1.setText(_translate("MainWindow", "Score 1"))
        self.labelScore2.setText(_translate("MainWindow", "Score 2"))
        self.labelScore3.setText(_translate("MainWindow", "Score 3"))
        self.labelScore4.setText(_translate("MainWindow", "Score 4"))
        self.pushButtonCalculate.setText(_translate("MainWindow", "Submit"))
